/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ChainTrack {
  export type CheckpointStruct = {
    id: BigNumberish;
    packageId: BigNumberish;
    agentId: BigNumberish;
    location: string;
    timestamp: BigNumberish;
    status: BigNumberish;
  };

  export type CheckpointStructOutput = [
    id: bigint,
    packageId: bigint,
    agentId: bigint,
    location: string,
    timestamp: bigint,
    status: bigint
  ] & {
    id: bigint;
    packageId: bigint;
    agentId: bigint;
    location: string;
    timestamp: bigint;
    status: bigint;
  };
}

export interface ChainTrackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bookShipment"
      | "cancelShipment"
      | "checkpointCtr"
      | "checkpoints"
      | "confirmDelivery"
      | "getCheckpoints"
      | "getPackage"
      | "getReceiptHash"
      | "getTransaction"
      | "logCheckpoint"
      | "owner"
      | "packageCtr"
      | "packageIdByCode"
      | "packages"
      | "receiptHashes"
      | "recordReceipt"
      | "registerUser"
      | "transactions"
      | "txnCtr"
      | "userCtr"
      | "userIdByAddress"
      | "users"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CheckpointLogged"
      | "DeliveryConfirmed"
      | "EscrowReleased"
      | "PackageBooked"
      | "ReceiptRecorded"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bookShipment",
    values: [
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelShipment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkpointCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkpoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCheckpoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPackage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logCheckpoint",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "packageCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "packageIdByCode",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "packages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiptHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordReceipt",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "txnCtr", values?: undefined): string;
  encodeFunctionData(functionFragment: "userCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userIdByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "bookShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkpointCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCheckpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPackage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logCheckpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "packageCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "packageIdByCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "packages", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiptHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "txnCtr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userIdByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
}

export namespace CheckpointLoggedEvent {
  export type InputTuple = [
    checkpointId: BigNumberish,
    packageId: BigNumberish,
    location: string,
    status: BigNumberish
  ];
  export type OutputTuple = [
    checkpointId: bigint,
    packageId: bigint,
    location: string,
    status: bigint
  ];
  export interface OutputObject {
    checkpointId: bigint;
    packageId: bigint;
    location: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [packageId: BigNumberish, confirmedBy: BigNumberish];
  export type OutputTuple = [packageId: bigint, confirmedBy: bigint];
  export interface OutputObject {
    packageId: bigint;
    confirmedBy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    txnId: BigNumberish,
    packageId: BigNumberish,
    payee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    txnId: bigint,
    packageId: bigint,
    payee: string,
    amount: bigint
  ];
  export interface OutputObject {
    txnId: bigint;
    packageId: bigint;
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PackageBookedEvent {
  export type InputTuple = [
    packageId: BigNumberish,
    qrHash: string,
    senderId: BigNumberish,
    receiverId: BigNumberish,
    amount: BigNumberish,
    currency: string
  ];
  export type OutputTuple = [
    packageId: bigint,
    qrHash: string,
    senderId: bigint,
    receiverId: bigint,
    amount: bigint,
    currency: string
  ];
  export interface OutputObject {
    packageId: bigint;
    qrHash: string;
    senderId: bigint;
    receiverId: bigint;
    amount: bigint;
    currency: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptRecordedEvent {
  export type InputTuple = [
    packageId: BigNumberish,
    recordedBy: BigNumberish,
    receiptHash: BytesLike
  ];
  export type OutputTuple = [
    packageId: bigint,
    recordedBy: bigint,
    receiptHash: string
  ];
  export interface OutputObject {
    packageId: bigint;
    recordedBy: bigint;
    receiptHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    userId: BigNumberish,
    role: BigNumberish,
    addr: AddressLike,
    name: string
  ];
  export type OutputTuple = [
    userId: bigint,
    role: bigint,
    addr: string,
    name: string
  ];
  export interface OutputObject {
    userId: bigint;
    role: bigint;
    addr: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainTrack extends BaseContract {
  connect(runner?: ContractRunner | null): ChainTrack;
  waitForDeployment(): Promise<this>;

  interface: ChainTrackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bookShipment: TypedContractMethod<
    [
      _qrHash: string,
      _contentHash: string,
      _weight: BigNumberish,
      _size: string,
      _receiverId: BigNumberish,
      _deliveryCodeHash: BytesLike,
      _currency: string
    ],
    [bigint],
    "payable"
  >;

  cancelShipment: TypedContractMethod<
    [_packageId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkpointCtr: TypedContractMethod<[], [bigint], "view">;

  checkpoints: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint, bigint] & {
        id: bigint;
        packageId: bigint;
        agentId: bigint;
        location: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  confirmDelivery: TypedContractMethod<
    [_packageId: BigNumberish, _deliveryCode: string, _receiptHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getCheckpoints: TypedContractMethod<
    [_packageId: BigNumberish],
    [ChainTrack.CheckpointStructOutput[]],
    "view"
  >;

  getPackage: TypedContractMethod<
    [_packageId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        qrHash: string;
        contentHash: string;
        weight: bigint;
        size: string;
        senderId: bigint;
        receiverId: bigint;
        activeAgentId: bigint;
        status: bigint;
        createdAt: bigint;
        deliveredAt: bigint;
      }
    ],
    "view"
  >;

  getReceiptHash: TypedContractMethod<
    [_packageId: BigNumberish],
    [string],
    "view"
  >;

  getTransaction: TypedContractMethod<
    [_txnId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint, bigint] & {
        packageId: bigint;
        senderId: bigint;
        receiverId: bigint;
        amount: bigint;
        currency: string;
        status: bigint;
        createdAt: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;

  logCheckpoint: TypedContractMethod<
    [_packageId: BigNumberish, _location: string, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  packageCtr: TypedContractMethod<[], [bigint], "view">;

  packageIdByCode: TypedContractMethod<[arg0: string], [bigint], "view">;

  packages: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        qrHash: string;
        contentHash: string;
        weight: bigint;
        size: string;
        senderId: bigint;
        receiverId: bigint;
        activeAgentId: bigint;
        status: bigint;
        createdAt: bigint;
        deliveredAt: bigint;
        deliveryCodeHash: string;
      }
    ],
    "view"
  >;

  receiptHashes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  recordReceipt: TypedContractMethod<
    [_packageId: BigNumberish, _receiptHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [_address: AddressLike, _name: string, _phone: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        packageId: bigint;
        senderId: bigint;
        receiverId: bigint;
        amount: bigint;
        currency: string;
        status: bigint;
        createdAt: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;

  txnCtr: TypedContractMethod<[], [bigint], "view">;

  userCtr: TypedContractMethod<[], [bigint], "view">;

  userIdByAddress: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  users: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        addr: string;
        id: bigint;
        name: string;
        phone: string;
        role: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bookShipment"
  ): TypedContractMethod<
    [
      _qrHash: string,
      _contentHash: string,
      _weight: BigNumberish,
      _size: string,
      _receiverId: BigNumberish,
      _deliveryCodeHash: BytesLike,
      _currency: string
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelShipment"
  ): TypedContractMethod<[_packageId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkpointCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkpoints"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint, bigint] & {
        id: bigint;
        packageId: bigint;
        agentId: bigint;
        location: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<
    [_packageId: BigNumberish, _deliveryCode: string, _receiptHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCheckpoints"
  ): TypedContractMethod<
    [_packageId: BigNumberish],
    [ChainTrack.CheckpointStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPackage"
  ): TypedContractMethod<
    [_packageId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        qrHash: string;
        contentHash: string;
        weight: bigint;
        size: string;
        senderId: bigint;
        receiverId: bigint;
        activeAgentId: bigint;
        status: bigint;
        createdAt: bigint;
        deliveredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptHash"
  ): TypedContractMethod<[_packageId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [_txnId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, string, bigint, bigint, bigint] & {
        packageId: bigint;
        senderId: bigint;
        receiverId: bigint;
        amount: bigint;
        currency: string;
        status: bigint;
        createdAt: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "logCheckpoint"
  ): TypedContractMethod<
    [_packageId: BigNumberish, _location: string, _status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "packageCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "packageIdByCode"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "packages"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        qrHash: string;
        contentHash: string;
        weight: bigint;
        size: string;
        senderId: bigint;
        receiverId: bigint;
        activeAgentId: bigint;
        status: bigint;
        createdAt: bigint;
        deliveredAt: bigint;
        deliveryCodeHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiptHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "recordReceipt"
  ): TypedContractMethod<
    [_packageId: BigNumberish, _receiptHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _phone: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        packageId: bigint;
        senderId: bigint;
        receiverId: bigint;
        amount: bigint;
        currency: string;
        status: bigint;
        createdAt: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "txnCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userIdByAddress"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint, boolean] & {
        addr: string;
        id: bigint;
        name: string;
        phone: string;
        role: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CheckpointLogged"
  ): TypedContractEvent<
    CheckpointLoggedEvent.InputTuple,
    CheckpointLoggedEvent.OutputTuple,
    CheckpointLoggedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "PackageBooked"
  ): TypedContractEvent<
    PackageBookedEvent.InputTuple,
    PackageBookedEvent.OutputTuple,
    PackageBookedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptRecorded"
  ): TypedContractEvent<
    ReceiptRecordedEvent.InputTuple,
    ReceiptRecordedEvent.OutputTuple,
    ReceiptRecordedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "CheckpointLogged(uint256,uint256,string,uint8)": TypedContractEvent<
      CheckpointLoggedEvent.InputTuple,
      CheckpointLoggedEvent.OutputTuple,
      CheckpointLoggedEvent.OutputObject
    >;
    CheckpointLogged: TypedContractEvent<
      CheckpointLoggedEvent.InputTuple,
      CheckpointLoggedEvent.OutputTuple,
      CheckpointLoggedEvent.OutputObject
    >;

    "DeliveryConfirmed(uint256,uint256)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "EscrowReleased(uint256,uint256,address,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "PackageBooked(uint256,string,uint256,uint256,uint256,string)": TypedContractEvent<
      PackageBookedEvent.InputTuple,
      PackageBookedEvent.OutputTuple,
      PackageBookedEvent.OutputObject
    >;
    PackageBooked: TypedContractEvent<
      PackageBookedEvent.InputTuple,
      PackageBookedEvent.OutputTuple,
      PackageBookedEvent.OutputObject
    >;

    "ReceiptRecorded(uint256,uint256,bytes32)": TypedContractEvent<
      ReceiptRecordedEvent.InputTuple,
      ReceiptRecordedEvent.OutputTuple,
      ReceiptRecordedEvent.OutputObject
    >;
    ReceiptRecorded: TypedContractEvent<
      ReceiptRecordedEvent.InputTuple,
      ReceiptRecordedEvent.OutputTuple,
      ReceiptRecordedEvent.OutputObject
    >;

    "UserRegistered(uint256,uint8,address,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
